# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WiserSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'WiserSmartBaseKit', :path => '../'
  pod 'WiserSmartUtil', :path => '../'
  pod 'WiserSmartMQTTChannelKit', :path => '../'
  pod 'WiserSmartSocketChannelKit', :path => '../'
  pod 'WiserSmartActivatorKit', :path => '../'
  pod 'WiserSmartDeviceKit', :path => '../'

#pod 'WiserSmartBaseKit', :git => 'https://github.com/sewiser/WiserSDK_IOS.git', :tag => '3.14.2'
#pod 'WiserSmartUtil', :git => 'https://github.com/sewiser/WiserSDK_IOS.git', :tag => '3.14.2'
#pod 'WiserSmartMQTTChannelKit', :git => 'https://github.com/sewiser/WiserSDK_IOS.git', :tag => '3.14.2'
#pod 'WiserSmartSocketChannelKit', :git => 'https://github.com/sewiser/WiserSDK_IOS.git', :tag => '3.14.2'
#pod 'WiserSmartActivatorKit', :git => 'https://github.com/sewiser/WiserSDK_IOS.git', :tag => '3.14.2'
#pod 'WiserSmartDeviceKit', :git => 'https://github.com/sewiser/WiserSDK_IOS.git', :tag => '3.14.2'

end
