//
//  WiserSmartDeviceEventUtil.h
//  WiserSmartDeviceCoreKit
//
//  Copyright (c) 2014-2021 Wiser Inc. (https://developer.wiser.com)

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, WSEventPipelineType) {
    /// LAN
    WSEventPipelineTypeLAN      = 1,
    
    /// MQTT
    WSEventPipelineTypeMQTT     = 2,
    
    /// HTTP
    WSEventPipelineTypeHTTP     = 3,
    
    /// Single Point Bluetooth
    WSEventPipelineTypeBLE      = 4,
    
    /// Sig Mesh
    WSEventPipelineTypeSIGMesh  = 5,
    
    /// Wiser Private Mesh
    WSEventPipelineTypeBLEMesh  = 6,
    
    /// others
    WSEventPipelineTypeOther    = 9,
};


@interface WiserSmartDeviceEventUtil : NSObject

/// Message sent request  successful.
///
/// @param pipelineType Message sending pipeline
+ (void)successEventWithPipelineType:(WSEventPipelineType)pipelineType;

/// Message sent request  failed.
///
/// @param pipelineType Message sending pipeline.
/// @param pv The pv of the device when the message is sent.
/// @param error The error generated by the message
/// @param extendInfo Detailed error information, you can easily check the status of the error and the app situation.
+ (void)failedEventWithPipelineType:(WSEventPipelineType)pipelineType
                                 pv:(double)pv
                              error:(NSError *)error
                         extendInfo:(NSDictionary *)extendInfo;

@end

NS_ASSUME_NONNULL_END
